DROP TABLE IF EXISTS `m_post`;

CREATE TABLE `m_post` (
                          `id` int(11) NOT NULL AUTO_INCREMENT,
                          `post_desc` varchar(200) COLLATE utf8_unicode_ci DEFAULT NULL,
                          `cat_id` int(3) DEFAULT NULL,
                          `rank_id` int(3) DEFAULT NULL,
                          `status` int(1) DEFAULT 1,
                          PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=227 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

/*Data for the table `m_post` */

insert  into `m_post`(`id`,`post_desc`,`cat_id`,`rank_id`,`status`) values
                                                                        (1,'Director General of Police',1,1,1),
                                                                        (2,'Additional Director General of Police',1,2,1),
                                                                        (3,'Inspector General of Police',1,3,1),
                                                                        (4,'Deputy Inspector General of Police',1,4,1),
                                                                        (5,'Superintendent of Police IPS',1,5,1),
                                                                        (6,'Assistant Superintendent of Police',1,NULL,1),
                                                                        (7,'Superintendnet of Police Non-IPS',2,NULL,1),
                                                                        (8,'Deputy Superintendent of Police/AC',2,6,1),
                                                                        (9,'Inspector of Police',2,7,1),
                                                                        (10,'Sub Inspector of Police',2,8,1),
                                                                        (11,'Assistant Sub Inspector of Police',2,9,1),
                                                                        (12,'SENIOR CIVIL POLICE OFFICER',2,10,1),
                                                                        (13,'CIVIL POLICE OFFICER',2,11,1),
                                                                        (14,'Superintedent of Police Women',2,NULL,1),
                                                                        (15,'Deputy Superintendent of Police Women',2,NULL,1),
                                                                        (16,'Women Inspector',2,NULL,1),
                                                                        (17,'Women Sub Inspector',2,NULL,1),
                                                                        (18,'Women Head Constable',2,NULL,1),
                                                                        (19,'Women Police Constable',2,73,1),
                                                                        (20,'Recruit Training Police Constable',2,NULL,1),
                                                                        (21,'Commandant AR',4,NULL,1),
                                                                        (22,'Deputy Commandant AR',4,NULL,1),
                                                                        (23,'Assistant Commandant AR',4,NULL,1),
                                                                        (24,'Reserve Inspector',4,NULL,1),
                                                                        (25,'Reserve Sub Inspector',4,NULL,1),
                                                                        (26,'Reserve Assistant Sub Inspector',4,NULL,1),
                                                                        (27,'Head Constable AR',4,NULL,1),
                                                                        (28,'Police Constable AR',4,NULL,1),
                                                                        (29,'Commandant APB',4,NULL,1),
                                                                        (30,'Deputy Commandant APB',4,NULL,1),
                                                                        (31,'Assistant Commandant APB',4,NULL,1),
                                                                        (32,'Armed Police Inspector',4,NULL,1),
                                                                        (33,'Armed Police Sub Inspector',4,NULL,1),
                                                                        (34,'Armed Police Assistant Sub Inspector',4,NULL,1),
                                                                        (35,'Head Constable APB',4,NULL,1),
                                                                        (36,'Head Constable IRB',4,NULL,1),
                                                                        (37,'Police Constable APB',4,NULL,1),
                                                                        (38,'Police Constable IRB',4,NULL,1),
                                                                        (39,'Superintendent of Police Tele',6,NULL,1),
                                                                        (40,'Deputy Superintendent of Police Tele',6,NULL,1),
                                                                        (41,'Inspector of Police Tele',6,NULL,1),
                                                                        (42,'Sub Inspector of Police Tele',6,NULL,1),
                                                                        (43,'Assistant Sub Inspector of Police Tele',6,NULL,1),
                                                                        (44,'Head Constable Tele',6,NULL,1),
                                                                        (45,'Police Constable Tele',6,NULL,1),
                                                                        (46,'Accounts Officer',7,NULL,1),
                                                                        (47,'Administrative Assistant',7,13,1),
                                                                        (48,'Assistant Director',7,NULL,1),
                                                                        (49,'Attender',7,25,1),
                                                                        (50,'Auxilary Nurse Midwife',5,NULL,1),
                                                                        (51,'Binder',7,27,1),
                                                                        (52,'Camp Follower',7,30,1),
                                                                        (53,'Cashier',7,NULL,1),
                                                                        (54,'Chief Law Instructor',7,NULL,1),
                                                                        (55,'Chief Photographer',5,NULL,1),
                                                                        (56,'Chief Reporter',5,NULL,1),
                                                                        (57,'Chief Store Keeper',7,NULL,1),
                                                                        (58,'Clerk',7,18,1),
                                                                        (59,'Clerk cum Typist',7,21,1),
                                                                        (60,'Computer Operator',7,NULL,1),
                                                                        (61,'Confidential Assistant',7,22,1),
                                                                        (62,'Cook (Hospital)',5,NULL,1),
                                                                        (63,'Deputy Director',7,NULL,1),
                                                                        (64,'Director',7,NULL,1),
                                                                        (65,'Fair Copy Superintendent',7,19,1),
                                                                        (66,'Full Time Sweeper',7,32,1),
                                                                        (67,'Head Accountant',7,NULL,1),
                                                                        (68,'Head Clerk',7,16,1),
                                                                        (69,'Head Nurse',5,NULL,1),
                                                                        (70,'Head of Department KEPA',5,NULL,1),
                                                                        (71,'Hospital Attendant',5,NULL,1),
                                                                        (72,'Inspecting Store Accountant',7,NULL,1),
                                                                        (73,'Joint Director',7,NULL,1),
                                                                        (74,'JPH Nurse',5,NULL,1),
                                                                        (75,'Junior Superintendent',7,15,1),
                                                                        (76,'Lascar',7,33,1),
                                                                        (77,'Legal Advisor',5,NULL,1),
                                                                        (78,'Librarian',7,23,1),
                                                                        (79,'Livestock Inspector',5,NULL,1),
                                                                        (80,'Lower Division Typist',7,NULL,1),
                                                                        (81,'Malayalam Transilator',7,24,1),
                                                                        (82,'Manager',7,NULL,1),
                                                                        (83,'Medico Legal Advisor',5,NULL,1),
                                                                        (84,'Nursing Assistant',5,NULL,1),
                                                                        (85,'Office Attendant',7,29,1),
                                                                        (86,'Packer',7,28,1),
                                                                        (87,'Pharmacist',5,NULL,1),
                                                                        (88,'Photographer',5,NULL,1),
                                                                        (89,'Photographic Attender',5,NULL,1),
                                                                        (90,'Principal',7,NULL,1),
                                                                        (91,'Range Warden',5,31,1),
                                                                        (92,'Roneo Operator',7,26,1),
                                                                        (93,'SB Assistant',7,NULL,1),
                                                                        (94,'Scientific Officer',5,NULL,1),
                                                                        (95,'Selection Grade Typist',7,NULL,1),
                                                                        (96,'Senior Administrative Assistant',7,12,1),
                                                                        (97,'Senior Clerk',7,17,1),
                                                                        (98,'Senior Finance Officer',5,NULL,1),
                                                                        (99,'Senior Grade Typist',7,NULL,1),
                                                                        (100,'Senior Law Instructor',7,NULL,1),
                                                                        (101,'Senior Superintendent',7,14,1),
                                                                        (102,'Staff Nurse',5,NULL,1),
                                                                        (103,'Statistical Assistant',5,NULL,1),
                                                                        (104,'Statistical Officer',5,NULL,1),
                                                                        (105,'Store Accountant',7,NULL,1),
                                                                        (106,'Technical Attender',5,NULL,1),
                                                                        (107,'Tester Inspector',5,NULL,1),
                                                                        (108,'Upper Division Typist',7,NULL,1),
                                                                        (109,'Vice Principal',7,NULL,1),
                                                                        (110,'COOK',8,NULL,1),
                                                                        (111,'BARBER',8,NULL,1),
                                                                        (112,'DHOBBY',8,NULL,1),
                                                                        (113,'SWEEPER CUM SANITARY WORKER',8,NULL,1),
                                                                        (114,'WATER CARRIER',8,NULL,1),
                                                                        (115,'COBBLER',8,NULL,1),
                                                                        (117,'CF(NOT CATEGORISED)',8,NULL,1),
                                                                        (118,'ARMOUR DySP',9,NULL,1),
                                                                        (119,'ARMOUR INSPECTOR',9,NULL,1),
                                                                        (120,'ARMOUR SUB INSPECTOR OF POLICE',9,NULL,1),
                                                                        (121,'ARMOUR ASSISTANT SUB INSPECTOR OF POLICE',9,NULL,1),
                                                                        (122,'ARMOUR HEAD CONSTABLE',9,NULL,1),
                                                                        (123,'ARMOUIR POLICE CONSTABLE',9,NULL,1),
                                                                        (124,'BAND SUB INSPECTOR',10,NULL,1),
                                                                        (125,'BAND HAVILDAR',10,NULL,1),
                                                                        (126,'BAND POLICE CONSTABLE',10,NULL,1),
                                                                        (127,'BUGLER SUB INSPECTOR OF POLICE',10,NULL,1),
                                                                        (128,'BUGLER ASSISTANT SUB INSPECTOR OF POLICE',10,NULL,1),
                                                                        (129,'BUGLER POLICE CONSTABLE',10,NULL,1),
                                                                        (130,'DRUMMER SUB INSPECTOR OF POLICE',10,NULL,1),
                                                                        (131,'DRUMMER ASSISTANT SUB INSPECTOR OF POLICE',10,NULL,1),
                                                                        (132,'DRUMMER POLICE CONSTABLE',10,NULL,1),
                                                                        (133,'ORCHESTRA SUB INSPECTOR OF POLICE',10,NULL,1),
                                                                        (134,'ORCHESTRA ASSISTANT SUB INSPECTOR OF POLICE',10,NULL,1),
                                                                        (135,'ORCHESTRA POLICE CONSTABLE',10,NULL,1),
                                                                        (136,'MOTOR TRANSPORT DySP',11,NULL,1),
                                                                        (137,'MOTOR TRANSPORT INSPECTOR',11,NULL,1),
                                                                        (138,'MOTOR TRANSPORT SUB INSPECTOR OF POLICE',11,NULL,1),
                                                                        (139,'MECH ASSISTANT SUB INSPECTOR OF POLICE',11,NULL,1),
                                                                        (140,'MECH HAVILDAR',11,NULL,1),
                                                                        (141,'FITTER/MECH POLICE CONSTABLE',11,NULL,1),
                                                                        (142,'ELECTRICAL POLICE CONSTABLE',11,NULL,1),
                                                                        (143,'CLEANER POLICE CONSTABLE',11,NULL,1),
                                                                        (144,'SUB INSPECTOR DRIVER',11,NULL,1),
                                                                        (145,'POLICE CONSTABLE  DRIVER',11,NULL,1),
                                                                        (146,'MOTOR CYCLE RIDER',11,NULL,1),
                                                                        (147,'Director FSL',5,34,1),
                                                                        (148,'Joint Director FSL',5,35,1),
                                                                        (149,'Assistant Director FSL',5,36,1),
                                                                        (151,'Mechanic FSL',5,38,1),
                                                                        (152,'Lab Technician',5,39,1),
                                                                        (154,'Director FPB',5,41,1),
                                                                        (155,'Deputy Director FPB',5,42,1),
                                                                        (157,'Finger Print Expert',5,44,1),
                                                                        (158,'Finger Print Searcher',5,45,1),
                                                                        (162,'Director SHB',5,49,1),
                                                                        (164,'Reporter',5,51,1),
                                                                        (165,'System Analyst/Program-Manager',5,52,1),
                                                                        (166,'Criminologist',5,54,1),
                                                                        (167,'Assistant Surgeon',5,55,1),
                                                                        (223,'SUB INSPECTOR OF POLICE AR (TRAINEE',4,NULL,1),
                                                                        (222,'SUB INSPECTOR OF POLICE APBN (TRAINEE)',4,NULL,1),
                                                                        (225,'SUB INSPECTOR OF POLICE GE (TRAINEE)',4,NULL,1),
                                                                        (181,'Deputy Director PIC',5,69,1),
                                                                        (221,'Additional Superintendnet of Police',2,NULL,1),
                                                                        (220,'PART TIME SWEEPER',8,NULL,1),
                                                                        (184,'TAILOR POLICE CONSTABLE',3,NULL,1),
                                                                        (185,'CARPENTER POLICE CONSTABLE',3,NULL,1),
                                                                        (186,'PAINTER POLICE CONSTABLE',3,NULL,1),
                                                                        (187,'CINEMA OPERATOR POLICE CONSTABLE',3,NULL,1),
                                                                        (188,'LATHE OPERATOR POLICE CONSTABLE',3,NULL,1),
                                                                        (189,'BLAKSMITH POLICE CONSTABLE',3,NULL,1),
                                                                        (190,'MASON POLICE CONSTABLE',3,NULL,1),
                                                                        (191,'MACHANIST POLICE CONSTABLE',3,NULL,1),
                                                                        (192,'UPHOLSTER POLICE CONSTABLE',3,NULL,1),
                                                                        (193,'WELDER POLICE CONSTABLE',3,NULL,1),
                                                                        (194,'FARRIER POLICE CONSTABLE',3,NULL,1),
                                                                        (195,'BINDER POLICE CONSTABLE',3,NULL,1),
                                                                        (196,'Fitter Police Constable',3,NULL,1),
                                                                        (197,'TRANSPORT COMMISSIONER',11,2,1),
                                                                        (198,'ADDITIONAL TRANSPORT COMMISSIONER',11,2,1),
                                                                        (199,'HEAD CONSTABLE DRIVER',11,NULL,1),
                                                                        (200,'WOMAN CIVIL POLICE OFFICER',4,NULL,1),
                                                                        (201,'WOMAN HEAD CONSTABLE',4,NULL,1),
                                                                        (202,'WOMAN ASSISTANT SUB INSPECTOR OF POLICE',4,NULL,1),
                                                                        (203,'WOMAN SUB INSPECTOR OF POLICE',4,NULL,1),
                                                                        (204,'ASSISTANT INSPECTOR GENERAL OF POLICE',1,5,1),
                                                                        (205,'ASSISTANT SUB INSPECTOR OF POLICER DRIVER',11,NULL,1),
                                                                        (206,'BUGLER HEAD CONSTABLE',10,NULL,1),
                                                                        (207,'ASSISTANT GRADE I',7,NULL,1),
                                                                        (208,'ASSISTANT GRADE II',7,NULL,1),
                                                                        (209,'SUB INSPECTOR OF POLICE(Gr)',2,8,1),
                                                                        (210,'SUB INSPECTOR OF POLICE(SN)',2,8,1),
                                                                        (211,'ASSISTANT SUB INSPECTOR OF POLICE(Gr)',2,8,1),
                                                                        (212,'UPPER DIVISION CLERK',7,18,1),
                                                                        (213,'DRAFTMAN',7,NULL,1),
                                                                        (214,'ASSISTANT DIRECTOR(VETERINARY)',7,NULL,1),
                                                                        (215,'BOAT LASCAR',7,NULL,1),
                                                                        (216,'BOAT SYARANG',7,NULL,1),
                                                                        (217,'Head of Department (Law)(AGP 6000)',7,NULL,1),
                                                                        (218,'RESEARCH OFFICER',7,NULL,1),
                                                                        (219,'SECTION OFFICER',7,NULL,1),
                                                                        (226,'JOINT SUPERINTENDENT OF POLICE',NULL,NULL,1);
